language: python
python:
  - "2.7_with_system_site_packages"
  - "3.2_with_system_site_packages"
  - "3.4"
install:
    - "pip install -r requirements.txt --use-mirrors"
script:
  - "python -m test_command && python -m unittest discover findtui.tests 'test_*.py'"
